# --------------------------------------------------------------------------
# WORKFLOW: DEPLOY WEBSITE TO TEST SERVER
# --------------------------------------------------------------------------
# This workflow will deploy the website to the backup test server when:
# - a commit is pushed on the 'main' branch
# --------------------------------------------------------------------------

# The name of the workflow
name: Automatic Deploy to Server (Test)

# The workflow will only execute when a push is made on main branch
on:
  push:
    branches:
      - main
      
# Run only the most recent workflow and cancel current ones
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# Run specific jobs for the workflow
jobs:
  
  SFTP-Mirror:
    name: SFTP Mirror
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    # Mirror files from GitHub repository to a remote server using SFTP
    - name: Test Server - SFTP Mirror (Full)
      uses: pyxn/sftp-mirror@v2.0.0
      env:
        HOSTNAME: ${{ secrets.HOSTNAME_TEST }}
        USERNAME: ${{ secrets.USERNAME_TEST }}
        PASSWORD: ${{ secrets.PASSWORD_TEST }}
        PATH_LOCAL: "./public_html/"
        PATH_REMOTE: "./newcitybetterlife.com/public_html/project/"
        PROTOCOL: sftp
        PORT: 22
        ARGS: --verbose --overwrite --delete 
        MODE: mirror_full

    # Creates a server-only configuration file
    - name: Test Server - SFTP Mirror (File Create - sql-config.ini)
      uses: pyxn/sftp-mirror@v2.0.0
      env:
        HOSTNAME: ${{ secrets.HOSTNAME_TEST }}
        USERNAME: ${{ secrets.USERNAME_TEST }}
        PASSWORD: ${{ secrets.PASSWORD_TEST }}
        PATH_REMOTE: "./newcitybetterlife.com/"
        PROTOCOL: sftp
        PORT: 22
        MODE: mirror_file_create
        CREATE_FILE_NAME: "sql-config.ini"
        CREATE_FILE_CONTENTS: "[database]\ndatabase = 'qiao6_comp3340'\nhostname = 'localhost'\nusername = '${{ secrets.USERNAME }}'\npassword = '${{ secrets.PASSWORD }}'"

    # Creates a server-only configuration file
    - name: Test Server - SFTP Mirror (File Create - map-config.js)
      uses: pyxn/sftp-mirror@v2.0.0
      env:
        HOSTNAME: ${{ secrets.HOSTNAME_TEST }}
        USERNAME: ${{ secrets.USERNAME_TEST }}
        PASSWORD: ${{ secrets.PASSWORD_TEST }}
        PATH_REMOTE: "./newcitybetterlife.com/public_html/scripts/"
        PROTOCOL: sftp
        PORT: 22
        MODE: mirror_file_create
        CREATE_FILE_NAME: "map-config.js"
        CREATE_FILE_CONTENTS: "let mapConfiguration = { token: '${{ secrets.MAPKIT_TOKEN_TEST }}' }"